[workspace]
members = ["programs/*", "client", "trident-tests/fuzz_tests"]
resolver = "1"

[profile.release]
overflow-checks = true
lto = "fat"
codegen-units = 1
panic = "abort"

[profile.release.build-override]
opt-level = 3
incremental = false
codegen-units = 1
